name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the code
        uses: actions/checkout@v2

      - name: Setting up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Installing dependencies
        run: npm install

      - name: Building the app
        run: npm run build

      - name: Deploying to cPanel
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          HOST: aladdinai.trade
          USERNAME: shorobin
          PORT: 22
          FOLDER: aladdin_server
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y openssh-client
          # Setup SSH key
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $PORT $HOST >> ~/.ssh/known_hosts
          # Sync files
          rsync -avz --delete -e "ssh -p $PORT" ./ $USERNAME@$HOST:$FOLDER
